name: Inno Store IaC

on:
  push:
    branches:
      - iac
    paths:
      - 'inno-store-iac/**'
      - '.github/workflows/inno-store-iac.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inno-store-iac

    steps:
      # GIT Checkout
      - uses: actions/checkout@main
      # Runs the bicep CLI action - individual files
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: inno-store-iac/main.bicep
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: U118053-sb-rg-iac
          template: ./main.json

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}

